const express=require('express');
const router=express.Router();
const ApprovalCtrl= require('./app/controllers/ApprovalController');
const Banks= require('./app/controllers/BanksController');
const basic= require('./app/controllers/basicController');
const Chat= require('./app/controllers/ChatController');
const CommonApi= require('./app/controllers/CommonApiController');
const Crate= require('./app/controllers/CrateController');
const File= require('./app/controllers/FileController');
const HrmsApi= require('./app/controllers/HrmsApiController');
const KpiReport= require('./app/controllers/KpiReportController');
const LogisticSummary= require('./app/controllers/LogisticSummaryController');
const MobileApiLogs= require('./app/controllers/MobileApiLogsController');
const Orders= require('./app/controllers/OrdersController');
const PurchaseReturn= require('./app/controllers/PurchaseReturnController');
const Signup= require('./app/controllers/SignupController');
const UpiEbutor= require('./app/controllers/UpiEbutorController');
const User= require('./app/controllers/UserController');
const VerifyDocs = require('./api/controllers/VerifyDocsController');


router.post('/approval/cycleCount', ApprovalCtrl.cycleCount);
router.post('/banks/getBankDetailByIFSC', Banks.getBankDetailByIFSC);
router.post('/basic/getBasicDetails', basic.getBasicDetails);
router.post('/chat/userGroups', Chat.userGroups);
router.post('/chat/joinUser', Chat.joinUser);
router.post('/chat/chatServer', Chat.chatServer);
router.post('/chat/ticketHistory', Chat.ticketHistory);
router.post('/chat/groupUsers', Chat.groupUsers);
router.post('/chat/assignTicket', Chat.assignTicket);
router.post('/chat/changeTicketStatus', Chat.changeTicketStatus);
router.post('/chat/getTicketsByStatus', Chat.getTicketsByStatus);
router.post('/chat/getOptions', Chat.getOptions);
router.post('/chat/updateReadStatus', Chat.updateReadStatus);
router.post('/chat/chatClient', Chat.chatClient);
router.post('/CommonApi/Stockistdashboard', CommonApi.Stockistdashboard);
router.post('/CommonApi/Stockistdetails', CommonApi.Stockistdetails);
router.post('/CommonApi/hrmsdashboard', CommonApi.hrmsdashboard);
router.post('/crate/getCrateDetails', Crate.getCrateDetails);
router.post('/crate/saveCrateVerification', Crate.saveCrateVerification);
router.post('/crate/getPickedCrateList', Crate.getPickedCrateList);
router.post('/crate/getProductReason', Crate.getProductReason);
router.post('/crate/saveWrongPickReason', Crate.saveWrongPickReason);
router.get('/crate/getReasonList', Crate.getReasonList);
router.post('/crate/getWrongPickedProducts', Crate.getWrongPickedProducts);
router.post('/file/uploadFile',File.uploadFile);
router.post('/hrmsApi/savepolicydetails',HrmsApi.savepolicydetails);
router.post('/hrmsApi/viewpolicies',HrmsApi.viewpolicies);
router.post('/kpiReport/Reports',KpiReport.Reports);
router.post('/logisticSummary/Reports',LogisticSummary.Reports);
router.post('/mobileapilogs/insertMobileApiLog',MobileApiLogs.insertMobileApiLog);
router.post('/orders/failed',Orders.failed);
router.post('/orders/FindUsers',Orders.FindUsers);
router.post('/orders/NativeCall',Orders.NativeCall);
router.post('/orders/SocketMsg',Orders.SocketMsg);
router.post('/purchaseReturn/getPRList',PurchaseReturn.getPRList);
router.post('/purchaseReturn/getPRDetails',PurchaseReturn.getPRDetails);
router.post('/purchaseReturn/assignPickerToPR',PurchaseReturn.assignPickerToPR);
router.post('/signup/signupall',Signup.signupall);
router.post('/upiebutor/UpiApp',UpiEbutor.UpiApp);
router.post('/upiebutor/CollectionRequest',UpiEbutor.CollectionRequest);
router.post('/upiebutor/checksum',UpiEbutor.checksum);
router.post('/upiebutor/GetToken',UpiEbutor.GetToken);
router.post('/upiebutor/CollectionStatus',UpiEbutor.CollectionStatus);
router.post('/upiebutor/CollectionRefund',UpiEbutor.CollectionRefund);
router.post('/upiebutor/makeid',UpiEbutor.makeid);
router.post('/upiebutor/listOfCollection',UpiEbutor.listOfCollection);
router.post('/upiebutor/listOfCollectionByDate',UpiEbutor.listOfCollectionByDate);
router.post('/user/create',User.create);
router.post('/verify-docs',VerifyDocs.getDocumentDetails);

module.exports=router;