const express=require('express');
const router=express.Router();
const Ordersctrl= require('./app/controllers/OrdersController');
const Routingctrl= require('./app/controllers/RoutingadminController');
const UpiEbutor= require('./app/controllers/UpiEbutorController');
const User= require('./app/controllers/UserController');
router.post('/Orders/index',Ordersctrl.index);
router.post('/Orders/failed', Ordersctrl.failed);
router.post('/Orders/FindUsers', Ordersctrl.FindUsers);
router.post('/Orders/NativeCall', Ordersctrl.NativeCall);
router.post('/Orders/SocketMsg', Ordersctrl.SocketMsg);
router.post('/Routingadmin/index', Routingctrl.index);
router.post('/Routingadmin/receiveOrdersList', Routingctrl.receiveOrdersList);
router.post('/Routingadmin/caclulateHubtoDesAll', Routingctrl.caclulateHubtoDesAll);
router.post('/Routingadmin/calculateDistance', Routingctrl.calculateDistance);
router.post('/Routingadmin/calculateDegree', Routingctrl.calculateDegree);
router.post('/Routingadmin/googledistanceMatrix', Routingctrl.googledistanceMatrix);
router.post('/Routingadmin/distanceApiGoogleMaps', Routingctrl.distanceApiGoogleMaps);
router.post('/Routingadmin/getDistance', Routingctrl.getDistance);
router.post('/Routingadmin/rad2degr', Routingctrl.rad2degr);
router.post('/Routingadmin/degr2rad', Routingctrl.degr2rad);
router.post('/Routingadmin/getLatLngCenter', Routingctrl.getLatLngCenter);
router.post('/Routingadmin/splitloadOnLocation', Routingctrl.splitloadOnLocation);
router.post('/Routingadmin/splitloadOnLocationClusterPackageNode', Routingctrl.splitloadOnLocationClusterPackageNode);
router.post('/Routingadmin/splitloadOnLocationOnOrderCountBaseBeat', Routingctrl.splitloadOnLocationOnOrderCountBaseBeat);
router.post('/Routingadmin/splitloadOnLocationOnOrderCount', Routingctrl.splitloadOnLocationOnOrderCount);
router.post('/Routingadmin/splitloadOnLocationOnOrderCount_ClusterPackageNode', Routingctrl.splitloadOnLocationOnOrderCount_ClusterPackageNode);
router.post('/Routingadmin/splitloadOnLocationbak', Routingctrl.splitloadOnLocationbak);
router.post('/Routingadmin/distributeOrders', Routingctrl.distributeOrders);
router.post('/Routingadmin/array_column', Routingctrl.array_column);
router.post('/Routingadmin/checkPointInsideThePolygon', Routingctrl.checkPointInsideThePolygon);
router.post('/Routingadmin/arrangeShortestPath', Routingctrl.arrangeShortestPath);
router.post('/Routingadmin/Dijiskstra', Routingctrl.Dijiskstra);
router.post('/Routingadmin/ShortestLookUp', Routingctrl.ShortestLookUp);
router.post('/Routingadmin/testPromise', Routingctrl.testPromise);
router.post('/UpiEbutor/UpiApp', UpiEbutor.UpiApp);
router.post('/UpiEbutor/CollectionRequest', UpiEbutor.CollectionRequest);
router.post('/UpiEbutor/checksum', UpiEbutor.checksum);
router.post('/UpiEbutor/GetToken', UpiEbutor.GetToken);
router.post('/UpiEbutor/CollectionStatus', UpiEbutor.CollectionStatus);
router.post('/UpiEbutor/CollectionRefund', UpiEbutor.CollectionRefund);
router.post('/UpiEbutor/makeid', UpiEbutor.makeid);
router.post('/UpiEbutor/listOfCollection', UpiEbutor.listOfCollection);
router.post('/UpiEbutor/UpiApp', UpiEbutor.UpiApp);
router.post('/UpiEbutor/listOfCollectionByDate', UpiEbutor.listOfCollectionByDate);
router.post('/User/create', User.create);
router.post('/User/index', User.index);

module.exports=router;